{% set name = "python-statemachine" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_statemachine-{{ version }}.tar.gz
  sha256: 5aabafa4b98a0b65a1d3d400707f7c86eae62f0ad1f233d7858f1bc4cef5dae0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core
    - pip
  run:
    - python >=3.7

test:
  imports:
    - statemachine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fgmacedo/python-statemachine
  summary: Python Finite State Machines made easy.
  license: MIT
  license_file: LICENSE
  doc_url: https://python-statemachine.readthedocs.io
  dev_url: https://github.com/fgmacedo/python-statemachine

extra:
  recipe-maintainers:
    - beenje
