{% set name = "python-statemachine" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_statemachine-{{ version }}.tar.gz
  sha256: 8ec2eef95ffe44b763d40b3923449c2c7f2b4940e1fb393e64fbe887692a4095

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core
    - pip
  run:
    - python >=3.7

test:
  imports:
    - statemachine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fgmacedo/python-statemachine
  summary: Python Finite State Machines made easy.
  license: MIT
  license_file: LICENSE
  doc_url: https://python-statemachine.readthedocs.io
  dev_url: https://github.com/fgmacedo/python-statemachine

extra:
  recipe-maintainers:
    - beenje
