schema_version: 1

context:
  name: python-statemachine
  version: "2.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python_statemachine-${{ version }}.tar.gz
  sha256: adda2e7327ed7ecc96069c49e830fcc8b11a5f9d899ab16742317167b3d7997d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - statemachine
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*

about:
  summary: Python Finite State Machines made easy.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/fgmacedo/python-statemachine
  repository: https://github.com/fgmacedo/python-statemachine
  documentation: https://python-statemachine.readthedocs.io

extra:
  recipe-maintainers:
    - beenje
